name: CD Pipeline - Deploy to EC2

on:
  workflow_run:
    workflows: ["CI Pipeline - Java Maven with SonarCloud"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Download artifact from CI
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: cicd-java-maven-artifact
          path: target

      # 2️⃣ Copy JAR to EC2
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/*.jar"
          target: "/home/ubuntu/app"

      # 3️⃣ Restart application on EC2
      - name: Restart application
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f jar || true
            nohup java -jar /home/ubuntu/app/*.jar > app.log 2>&1 &
